//>>>>> Headers section

#include <stdio.h>
#include <linux/limits.h>
#include <errno.h>
#include <sys/stat.h>
#include <unistd.h>
#include <dirent.h>

//>>>>> Macros section

//Test for existence.
#define F_OK 0
//Confirmation of existance of a file
#define FILE_EXISTS 1
//Confimration of non existance of a file
#define FILE_NEXISTS -2
//Confirmation of new creation of a file
#define FILE_CREATED 0
//Info that the check is for file
#define FILE_C 1
//Info that the check is for directory
#define DIR_C 0
//Error code for directory existance
#define EEXIST 17
//Confirmation of existance of a directory
#define DIR_EXISTS 1
//Confimration of non existance of a directory
#define DIR_NEXISTS -2
//Confirmation of creation of a directory
#define DIR_CREATED 0
//Movement representor [forward]
#define FORWARD 1 
//Movement representor [backward]
#define BACKWARD -1
//Confirmation of file
#define IS_FILE 1
//Confirmation of directory 
#define IS_DIR 0
//Information that file is a script file
#define IS_SCRIPT 1
//Information that file is not a script file
#define IS_NSCRIPT -1
//Information that path updator doesn't require /
#define NONEEDFS -1
//Information that path updator requires /
#define NEEDFS 1
//Confirmation that file has been removed
#define FILE_REMOVED 1
//Confirmation that file has been removed
#define FILE_NREMOVED -1
//Confirmation that directory has been removed
#define DIR_REMOVED 1
//Confirmation that file has been renamed
#define FILE_RENAMED 1
//Confirmation that directory has been renamed
#define DIR_RENAMED 1


//>>>>> Global variable section

//__RUN Variables

//variable used to tell the program whether to continue running or not 
int run = 1;
//variable used to tell the program whether to continue creating a structure of not once an operation is done
int run_create = 1;

//__FLAG Variables

//variable used to tell the create directory function if the directory is being created for structure or not
int dir_is_struct = 0;
//flag used to represent "check existance while updating the path" which will check if the path generated by the update_path() function is existing or not and if it doesnt exist then it will revert back to the old one
int cewup_flag = 0;

//__GENERAL Variables

//charecter pointers used for referencing strings if returning is hard 
char *gen_cpointer = NULL;
//charecter string used for path genral use case [try to avoid highly inefficient everytime usage is done the whole string should be cleared]
char gen_pathstring[PATH_MAX] = "\0";


//>>>>> Functions section

//__Utility functions

//function which will go to the next instruction upon clicking enter
void confirm_wait()
{
    //TODO bug gound : when you are typing more than a character unexpected things are occuring
    char confirm;
    printf("\nType q and ENTER to go back : ");
    scanf(" %c",&confirm);
}

//function which will create the illusion of clearing the terminal by printing a lot of "\n" [new line charecters] 
void clear_terminal()
{
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
}

//function which will print the current working path 
void fancy_path(char * path)
{
    printf("\n");
    printf("<<<<< Curr path : ");
    printf("%s >>>>>\n",path);
}

//function which will clear all the charecters that may currently exist in the "char gen_pathstring[PATH_MAX]"
void clear_pathstring()
{
    for(int i = 0 ; i < PATH_MAX; i++)
    {
        gen_pathstring[i] = '\0';
    }
}

//function which will set a flag 
void set_flag(void * flag)
{
    //TODO add a function to set a flag high
}

//create a function to give text formating

//Functions core to the program

//Function which will store the relative path to given path from mentioned number of ancestor directory in the char gen_pathstring[PATH_MAX]
//
//Note : it doesn't store a backslash when it is storing the result and there is no restriction of whether there should or shouldn't be a forwardslash at the end
int ansc_rel_path(char * cpath, int ancestor_number)
{
    //The array which stores the indexes of the backslashes it encountered. Expanded as [back_slash_index]
    int bsi[PATH_MAX];
    int bsi_pointer = 0;
    int required_backslash_index = 0;
    int lastbefore_backslash_index = 0;

    //This variable will be acting like a boolean for determining whether forward slash exists at the end of cpath or not.
    //
    //0 represents forward slash doesn't exist
    //1 represents forward slash exists
    int fse = 0;
    for(int i = 0 ; i < PATH_MAX; i++)
    {
        if(cpath[i] == '/')
        {
            if(cpath[i+1] != '\0')
            {
                bsi[bsi_pointer] = i;
                bsi_pointer++;
                continue;
            }
            else
            {
                bsi[bsi_pointer] = i;
                lastbefore_backslash_index = i;
                fse=1;
                break;
            }
        }
        else if(cpath[i] == '\0')
        {
            bsi_pointer--;
            if(bsi_pointer == -1)
            {
                printf("no forward slashes found error");
                return -2;
            }
            lastbefore_backslash_index = bsi[bsi_pointer];
            fse=0;
            break;
        }
    }

    if(fse == 1)
    {
        //This is the index of bsi[PATH_MAX] which will be storing the actual index location of the required backslash in cpath string
        int req_sindex = bsi_pointer - ancestor_number;
        required_backslash_index = bsi[req_sindex];
        int k = 0;
        for(int i = required_backslash_index+1; i<lastbefore_backslash_index; i++)
        {
            gen_pathstring[k] = cpath[i];
            k++;
        }
    }
    else if (fse == 0)
    {
        //This is the index of bsi[PATH_MAX] which will be storing the actual index location of the required backslash in cpath string
        //
        //Note : ancestor-1 is taken because the bsi_pointer without forward slash at the end of cpath string, will be pointing to the forward slash which would be second last if a forward slash was there
        int req_sindex = bsi_pointer - (ancestor_number-1);
        required_backslash_index = bsi[req_sindex];
        int k = 0;
        for(int i = required_backslash_index+1; i<PATH_MAX; i++)
        {
            gen_pathstring[k] = cpath[i];
            k++;
        }
    }
} 

//function to check existance of a file or directory 
int existance_checker(char *tpath)
{
    DIR *dirptr;
    if (access (tpath, F_OK) != -1 ) 
    {
        if ((dirptr = opendir (tpath)) != NULL) 
        {
            closedir (dirptr); 
            return IS_DIR;
        } 
        else 
        {
            return IS_FILE; 
        }
    } 
    else 
    {
        return FILE_NEXISTS;  
    }

}

//function to update the path [move between directories]
int update_path(char *cpath, char *addon, int movement, int slash_flag)
{
    if(movement == BACKWARD)
    {
        int lastbefore_backslash_index = 0;
        for(int i = 0 ; i < PATH_MAX; i++)
        {
            if(cpath[i] == '/')
            {
                if(cpath[i+1] != '\0')
                {
                    lastbefore_backslash_index = i;
                }
                else
                {
                    for(int j = lastbefore_backslash_index+1 ; j < NAME_MAX ; j++)
                    {
                        if(cpath[j] != '\0')
                        {
                            cpath[j] = '\0';
                        }
                        else
                        {
                            break;
                        }
                    }
    
                    break;
                }
            }
        }
    }

    else if (movement == FORWARD)
    {
        for(int i = 0 ; i < PATH_MAX ; i++)
        {
            if(cpath[i] != '\0')
            {
                continue;
            }
            else
            {
                int k = i;
                for(int j = 0 ; j < PATH_MAX ; j++)
                {
                    if(addon[j] != '\0')
                    {
                        cpath[k] = addon[j];
                        k++;
                        continue;
                    }
                    else
                    {
                        if(slash_flag == NEEDFS)
                        {
                            cpath[k] = '/';
                            k++;
                            cpath[k] = addon[j];
                            break;
                        }
                        else if (slash_flag == NONEEDFS)
                        {
                            cpath[k] = addon[j];
                            k++;
                            break;
                        }
                    }
                }

                if( (cewup_flag) && (existance_checker(cpath) == -2))
                {
                    //TODO check on this feature once I think it is not doing what it is intended to do
                    update_path(cpath,"\0",BACKWARD,NEEDFS);
                    printf("\nNo such directory exists\n");
                    return DIR_NEXISTS;
                }
                break;
            }
        }
    }
}

//function to generate a new path with current path and addon
int generate_path(char *rpath, char *cpath, char *addon)
{
    int index_of_null = 0;
    for(int i = 0 ; i <= PATH_MAX ; i++)
    {
        if(i == PATH_MAX)
        {
            index_of_null = i;
            rpath[i] = '\0';
            printf("\nPath size is overflowing...\ncancelling creation of file...\n");
            //TODO implement handling for file path exceding case 
            break;
        }
        if(cpath[i] == '\0')
        {
            index_of_null = i;
            rpath[i] = cpath[i];
            break;
        }
        else
        {
            rpath[i] = cpath[i];
            continue;
        }
    }

    int j = 0;
    for(int i = index_of_null; i <= PATH_MAX; i++)
    {
        if(i == PATH_MAX)
        {
            index_of_null = i;
            rpath[i] = '\0';
            printf("\npath size is overflowing...\ncancelling creation of file...\n");
            //TODO implement handling for file path exceding case 
            break;
        }
        if(addon[j] == '\0')
        {
            index_of_null = i;
            rpath[i] = addon[j];
            break;      
        }
        else
        {
            rpath[i] = addon[j];
            j++;
        }
    }

    return index_of_null;
}

//function to create a file
int create_file(char *cpath,int script_flag)
{
    //TODO make handling script files more efficient 

    //string which stores the name of the file to create the file
    char fname[NAME_MAX]="\0";

    //string which is used to store the path of the file to be created
    char fpath[PATH_MAX]="\0";
    
    clear_terminal();
    if(script_flag == IS_SCRIPT)
    {
        printf("Enter the name of the script file wtihout \".sh\" extention : ");
    }
    else if (script_flag == IS_NSCRIPT)
    {
        printf("Enter the name of the file : ");
    }
    scanf(" %[^\n]%*c" ,fname);
    
    generate_path(fpath, cpath, fname);
    if(script_flag == IS_SCRIPT)
    {
        generate_path(fpath,fpath,".sh");
    }

	FILE *fptr;
	if(access(fpath,F_OK) == 0)
	{
        printf("\nfile already exists!\ncancelling file creation...\n");
		return FILE_EXISTS;
	}
	else
	{
		fopen(fpath,"w");
		return FILE_CREATED;
	}
}

//function to create a directory
int create_directory(char *cpath)
{
    //string which stores the name of the directory to create the directory
    char dname[NAME_MAX]="\0";

    //string which is used to store the path of the directory to be created
    char dpath[PATH_MAX]="\0";
    
    clear_terminal();
    if(dir_is_struct ==  0)
    {
        printf("Enter the name of the directory : ");
    }
    else if (dir_is_struct == 1)
    {
        printf("Enter the name of the structure : ");
    }
    
    scanf(" %[^\n]%*c" ,dname);
    if(dir_is_struct ==  0)
    {
        generate_path(dpath,cpath,dname);
        if(!mkdir(dpath,0755))
        {
            return DIR_CREATED;
        }
        else if(errno == EEXIST)
        {
            printf("\nDirectory already exists\n");
            return DIR_EXISTS;
        }
        else
        {
            return -1;
        }
    }
    else if (dir_is_struct == 1)
    {
        generate_path(gen_pathstring,cpath,dname);
        if(!mkdir(gen_pathstring,0755))
        {
            return DIR_CREATED;
        }
        else if(errno == EEXIST)
        {
            printf("\nStructure already exists\n");
            return DIR_EXISTS;
        }
        else
        {
            return -1;
        }
    }
	
}

//function to remove a file 
int remove_file(char *cpath)
{
    clear_terminal();
    char fpath[PATH_MAX]="\0";
    char fname[NAME_MAX]="\0";
    printf("Enter file name here : ");
    scanf(" %[^\n]%*c",fname);
    generate_path(fpath,cpath,fname);
    int ret_val = existance_checker(fpath);
    
    if( ret_val == IS_FILE)
    {
        remove(fpath);
        return FILE_REMOVED;
    }
    else if(ret_val == FILE_NEXISTS)
    {
        return FILE_NREMOVED;
    }
}

//function to remove a directory
int remove_dir(char *dpath)
{
    int ret_val = existance_checker(dpath);
    
    if(ret_val == FILE_NEXISTS)
    {
        printf("No such Directory exists\nCancelling request\n");
    }
    else if(ret_val == IS_DIR)
    {
        DIR *d;
        struct dirent *dir;
        d = opendir(dpath);
        if(d)
        {
            while((dir = readdir(d)) != NULL)
            {
                if(dir->d_name[0] == '.')
                {
                    if(dir->d_name[1] == '.')
                    {
                        if(dir->d_name[2] == '\0')
                        {
                            continue;
                        }    
                    }
                    else if(dir->d_name[1] == '\0')
                    {
                        continue;
                    }
                    else
                    {
                        //TODO hidden directory case
                    }
                }
                else
                {
                    char tpath_in[PATH_MAX]="\0";
                    char tpath_out[PATH_MAX]="\0";
                    generate_path(tpath_in,dpath,"\0");
                    update_path(tpath_in,dir->d_name,FORWARD,NEEDFS);
                    generate_path(tpath_out,dpath,dir->d_name);
                    if (existance_checker(tpath_out) == IS_FILE)
                    {
                        remove(tpath_out);
                    }
                    else if(existance_checker(tpath_out) == IS_DIR)
                    {
                        remove_dir(tpath_in);
                    }
                }
            }            
            closedir(d);
            rmdir(dpath);
            return DIR_REMOVED;
        }
    }
    if(ret_val == IS_FILE)
    {
        remove(dpath);
    }
}

//function to rename a file/directory
int rename_FD(char *cpath, int FoD)
{
    clear_terminal();
    char oldname[NAME_MAX]="\0";
    char oldpath[PATH_MAX]="\0";
    char newname[NAME_MAX]="\0";
    char newpath[PATH_MAX]="\0";
    if(FoD == IS_FILE)
    {
        printf("Enter old file name here : ");
        scanf(" %[^\n]%*c",oldname);
        printf("\n\nEnter new file name here : ");
        scanf(" %[^\n]%*c",newname);
    }
    if(FoD == IS_DIR)
    {
        printf("Enter old directory name here : ");
        scanf(" %[^\n]%*c",oldname);
        printf("\n\nEnter new directory name here : ");
        scanf(" %[^\n]%*c",newname);
    }
    generate_path(oldpath,cpath,oldname);
    generate_path(newpath,cpath,newname);
    rename(oldpath,newpath);
    if(FoD == IS_FILE)
    {
        return FILE_RENAMED;
    }
    if(FoD == IS_DIR)
    {
       return DIR_RENAMED; 
    }
}

//function to list all the files in a directory
void list_contents(char *cpath)
{
    DIR *d;
    struct dirent *dir;
    d = opendir(cpath);
    if(d)
    {
        clear_terminal();
        while((dir = readdir(d)) != NULL)
        {
            printf("\n%s",dir->d_name);
        }
        confirm_wait();
        closedir(d);
        dir = NULL;
    }
}

// function to copy a file from one place to another place 
void copy_file(char *destpath, char *srcpath)
{
    char buffer[512] = "\0";
    size_t buffer_size = sizeof(buffer)/sizeof(buffer[0]);
    size_t bytes_read = 0;

    FILE *src_file = fopen(srcpath,"r");
    if(src_file == NULL)
    {
        printf("\nThe path of the source file is %s",srcpath);
        perror("Source file opening failed");
    }
    FILE *dest_file = fopen(destpath,"w+");
    if(dest_file == NULL)
    {
        printf("\nThe path of the destination file is %s",destpath);
        perror("Destination file opening failed");
    }

    while((bytes_read=fread(buffer,sizeof(char),buffer_size,src_file))>0)
    {
        fwrite(buffer, sizeof(char), bytes_read, dest_file);
    }

    fclose(src_file);
    fclose(dest_file);

    src_file = dest_file = NULL;
}

// function to copy a directory from one place to the other with contents recursively
int copy_dir(char *dest_path, char *dpath)
{
    // TODO maintain the current path inside the directory
    // TODO create new path for content both for destination and source

    int ret_val1 = existance_checker(dpath); 
    int ret_val2 = existance_checker(dest_path);
    if(ret_val1 == FILE_NEXISTS)
    {
        printf("Source Error : The path \"%s\" doesn't exist \nCancelling request\n",dpath);
        return -3;
    }
    // else if (ret_val2 == FILE_NEXISTS)
    // {
    //     printf("Destination Error : The path \"%s\" doesn't exist \nCancelling request\n",dest_path);
    //     return -3;
    // }
    else if(ret_val1 == IS_DIR)
    {
        DIR *d;
        struct dirent *dir;
        d = opendir(dpath);
        if(d)
        {
            //string which stores the path of the file/dir from source
            char tpath_s[PATH_MAX]="\0";

            //string which stores the path of the file/dir from destination
            char tpath_d[PATH_MAX]="\0";
            
            //this area expects your dest path to not have a '/' at the end of the path
            generate_path(tpath_d,dest_path,"/\0");
            generate_path(tpath_s,dpath,"\0");
            ansc_rel_path(tpath_s,1);
            update_path(tpath_d,gen_pathstring,FORWARD,NONEEDFS);
            clear_pathstring();
            if(!mkdir(tpath_d,0755))
            {
                //tester for checking directory creation
                if(1)
                {
                    printf("\n%s Directory created\n",tpath_d);
                }
            }
            else if(errno == EEXIST)
            {
                printf("\n%s Directory already exists\n",tpath_d);
                return DIR_EXISTS;
            }
            else
            {
                printf("\nunkown error occured while creating directory with path %s\n",tpath_d);
                return -3;
            }

            while((dir = readdir(d)) != NULL)
            {
                if(dir->d_name[0] == '.')
                {
                    if(dir->d_name[1] == '.')
                    {
                        if(dir->d_name[2] == '\0')
                        {
                            continue;
                        }    
                    }
                    else if(dir->d_name[1] == '\0')
                    {
                        continue;
                    }
                    else
                    {
                        //TODO hidden directory case
                    }
                }
                else
                {
                    //string which stores the path of the file/dir from source
                    char ttpath_d[PATH_MAX]="\0";
                    char ttpath_s[PATH_MAX]="\0";
                    generate_path(ttpath_d,tpath_d,"\0");
                    generate_path(ttpath_s,tpath_s,"/\0");
                    update_path(ttpath_s,dir->d_name,FORWARD,NONEEDFS);
                    copy_dir(ttpath_d,ttpath_s);
                }
            }            
            closedir(d);
            return DIR_REMOVED;
        }
        else
        {
            printf("error opening the directory with path %s",dpath);
            return -3;
        }
    }
    if(ret_val1 == IS_FILE)
    {
        //string which stores the path of the file/dir from source
        char tpath_s[PATH_MAX]="\0";

        //string which stores the path of the file/dir from destination
        char tpath_d[PATH_MAX]="\0";
        
        //this area expects your dest path to not have a '/' at the end of the path
        generate_path(tpath_d,dest_path,"/\0");
        generate_path(tpath_s,dpath,"\0");
        ansc_rel_path(tpath_s,1);
        update_path(tpath_d,gen_pathstring,FORWARD,NONEEDFS);
        clear_pathstring();

        //tester to check the destination and source paths
        if(0)
        {
            printf("\ndest is %s",tpath_d);
            printf("\nsource is %s",tpath_s);
        }
        copy_file(tpath_d,tpath_s);
    }

}

// function used to do operations in a strcuture 
void operator(char *cpath)
{
    while(run_create == 1)
    {
        clear_terminal();

        //variable used to know which operation needs to be performed while creating a structure 
        int choice_of_operation = 0;

        // clear_terminal();
        fancy_path(cpath);
        printf("1. Create a file");
        printf("\n2. Create a directory");
        printf("\n3. Create a script file");
        printf("\n4. Move into a directory");
        printf("\n5. Move to parent directory");
        printf("\n6. Remove a file");
        printf("\n7. Remove a directory");
        printf("\n8. Rename a file");
        printf("\n9. Renanme a directory");
        printf("\n10. List current path contents");
        printf("\n11. End making a structure\n");
        printf("\n\nEnter your choice : ");
        scanf("%d",&choice_of_operation);

        switch (choice_of_operation)
        {
            case 1:
            {
                int temp = create_file(cpath,IS_NSCRIPT);
                clear_terminal();
                if(temp == FILE_CREATED)
                {
                    printf("file successfully created");
                }
                break;
            }
            case 2:
            {
                int temp = create_directory(cpath);
                clear_terminal();
                if(temp == DIR_CREATED)
                {
                    printf("directory successfully created");
                }
                break;
            }
            case 3:
            {
                int temp = create_file(cpath,IS_SCRIPT);
                clear_terminal();
                if(temp == FILE_CREATED)
                {
                    printf("script file successfully created");
                }
                break;
            }
            case 4:
            {
                char tname[NAME_MAX]="\0";
                clear_terminal();
                printf("Enter the name of the directory : ");
                scanf(" %[^\n]%*c",tname);
                update_path(cpath,tname,FORWARD,NEEDFS);
                break;
            }
            case 5:
            {
                update_path(cpath,"\0",BACKWARD,NEEDFS);
                break;
            }
            case 6:
            {
                int temp = remove_file(cpath);
                clear_terminal();
                if(temp == FILE_REMOVED)
                {
                    printf("file removed successfully");
                }
                else if(temp == FILE_NREMOVED)
                {
                    printf("file was not removed");
                }
                break;
            }
            case 7:
            {
                char dname[NAME_MAX]="\0";
                clear_terminal();
                printf("\nEnter the directory name :\n");
                scanf(" %[^\n]%*c",dname);
                char dpath[PATH_MAX]="\0";
                generate_path(dpath,cpath,"\0");
                update_path(dpath,dname,FORWARD,NEEDFS);
                if (remove_dir(dpath) == DIR_REMOVED)
                {
                    clear_terminal();
                    printf("Directory removed succesfully");
                }
                break;
            }
            case 8:
            {
                if(rename_FD(cpath,IS_FILE) == FILE_RENAMED)
                {
                    clear_terminal();
                    printf("File has been successfully renamed");
                }          
                break;
            }
            case 9:
            {
                if(rename_FD(cpath,IS_DIR) == DIR_RENAMED)
                {
                    clear_terminal();
                    printf("Directory has been successfully renamed");
                }
                
                break;
            }
            case 10:
            {
                list_contents(cpath);
                break;
            }
            case 11:
            {
                run_create = 0;
                break;
            }
            default:
            {
                printf("\nfound invalid operation number, please enter a valid one\n");
                break;
            }
        }
    }  
    run_create = 1;  
    return;
}

//TODO create a function which will take a message [string] along with the during it should be shown onto the terminal  


int main()
{   
    while(run == 1)
    {
        //variable used to know what structure operation needs to be done
        int choice_of_struct = 0;

        //string used to store the path of presently operating directory [used when creating a structure]
        char path[PATH_MAX] = "./structures/\0";

        clear_terminal();
        printf("1. Create a structure");
        printf("\n2. Use a structure");
        printf("\n3. Remove a structure");
        printf("\n4. Edit a structure");
        printf("\n5. Stop the program\n");
        printf("\n\nEnter your choice : ");  
        scanf("%d",&choice_of_struct);

        switch (choice_of_struct)
        {
            case 1:
            {
                char sname[NAME_MAX]="\0";
                dir_is_struct = 1;
                create_directory(path);
                dir_is_struct = 0;
                operator(gen_pathstring);
                clear_pathstring(); 
                break;
            }
            case 2:
            {
                //TODO write code for using the created structures
                //show list of the structs
                char sname[NAME_MAX]="\0";
                list_contents(path);
                clear_terminal();
                printf("\nEnter the structure name to use : ");
                scanf(" %[^\n]%*c",sname);
                char spath[PATH_MAX]="\0";
                generate_path(spath,path,"\0");
                if(update_path(spath,sname,FORWARD,NONEEDFS) == DIR_NEXISTS)
                {
                    confirm_wait();
                }
                else
                {
                    clear_terminal();
                    char cwd_path[PATH_MAX]="\0";
                    if(getcwd(cwd_path,sizeof(cwd_path)) != NULL)
                    {
                        copy_dir(cwd_path,spath);
                    }
                    else
                    {
                        perror("Error in getting the current working directory path");
                    }
                }               
                break;
            }
            case 3:
            {
                char sname[NAME_MAX]="\0";
                list_contents(path);
                clear_terminal();
                printf("\nEnter the structure name to remove : ");
                scanf(" %[^\n]%*c",sname);
                char spath[PATH_MAX]="\0";
                generate_path(spath,path,"\0");
                if(update_path(spath,sname,FORWARD,NEEDFS) == DIR_NEXISTS)
                {
                    confirm_wait();
                }
                else if (remove_dir(spath) == DIR_REMOVED)
                {
                    clear_terminal();
                    printf("Structure removed succesfully");
                }               
                break;
            }
            case 4:
            {
                char sname[NAME_MAX]="\0";
                list_contents(path);
                printf("\nEnter the structure name to edit :");
                scanf(" %[^\n]%*c",sname);
                if (update_path(path,sname,FORWARD,NEEDFS) == DIR_NEXISTS)
                {
                    confirm_wait();
                }
                else
                {

                    operator(path);
                }
                break;
            }    
            case 5:
            {
                printf("\n<<<< exiting the program >>>>\n");
                run = 0;                
                break;
            }
            default:
            {
                printf("\nfound invalid operation number, please enter a valid one\n");
                break;
            }
        }
    }
    
    return 0;
}